[package]
name = "storage-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-spdk = {path=".."}
async-trait ="0.1"
log = "0.4"

[dev-dependencies]
env_logger = "0.8"